-- 코드를 입력하세요
SELECT 
MEMBER_ID, 
MEMBER_NAME, 
GENDER, 
DATE_FORMAT(DATE_OF_BIRTH ,'%Y-%m-%d') as date_of_birth
FROM MEMBER_PROFILE
WHERE GENDER = 'W'
 AND MONTH(date_of_birth) = '03'
 AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;