SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR
    , (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV
    , ID
FROM ECOLI_DATA AS E
    JOIN (
        SELECT 
            YEAR(DIFFERENTIATION_DATE) AS YEAR
            , MAX(SIZE_OF_COLONY) AS MAX_SIZE
        FROM ECOLI_DATA
        GROUP BY YEAR
        ) AS M
    ON M.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;